[flake8]
max-line-length = 150
exclude =
    aidrin/data
    aidrin/datasets
    aidrin/images
    aidrin/custom_metrics/remedy_data
    aidrin/custom_metrics/customDR_*.py
    web/static
    web/templates
