name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        channels: conda-forge
        activate-environment: aidrin

    - name: Conda info
      run: conda info

    - name: Conda list
      run: conda list

    - name: Install
      run: |
        conda run -n aidrin python --version
        conda run -n aidrin pip install -e .
