name: prettier

on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install prettier
        run: npm install prettier

      - name: Check CSS formatting
        run: npx prettier --check web/static/css

      - name: Check JavaScript formatting and syntax
        run: |
          npx prettier --check web/static/js
          node --check web/static/js/inspector.js
          node --check web/static/js/main.js
