name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        channels: conda-forge
        activate-environment: aidrin

    - name: Conda info
      run: conda info

    - name: Conda list
      run: conda list

    - name: Install Dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install setuptools==70.0.0
        pip install -e .
        pip install pytest pytest-flask pytest-cov

    - name: Run unit tests
      shell: bash -l {0}
      run: |
        python -c "import pkg_resources; print('pkg_resources found')"
        PYTHONPATH=. pytest tests/unit/ -v --cov=aidrin --cov-report=term-missing

    - name: Run integration tests
      shell: bash -l {0}
      run: |
        PYTHONPATH=. pytest tests/integration/ -v
